name: fullfit_app
description: Proyecto DAM IFP.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.1 <4.0.0"

### PAQUETES ###
dependencies:
  cloud_firestore: ^4.7.1
  dots_indicator: ^3.0.0
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  firebase_storage: ^11.2.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_easyloading: ^3.0.5
  flutter_riverpod: ^2.3.6
  flutter_screenutil: ^5.8.2
  fluttertoast: ^8.2.2
  formz: ^0.6.0
  go_router: ^7.1.1
  google_fonts: ^4.0.3
  google_sign_in: ^6.1.2
  image_picker: ^0.8.7+5
  permission_handler: ^10.2.0
  shared_preferences: ^2.1.1
  twitter_login: ^4.4.0

### PAQUETES DE DESARROLLO ###
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  ### ASSETS ###
  assets:
    - .env
    - assets/
    - assets/icons/
    - assets/images/
    - assets/loaders/
    - google_fonts/roboto/
